<?php

namespace Database\Seeders\Support;

final class PanelSpeciesCatalog
{
    /**
     * Twenty additions selected to bring the field guide to 30 total species.
     * These entries are educational only until a replacement CNN is trained.
     *
     * @return array<int, array<string, mixed>>
     */
    public static function entries(): array
    {
        return [
            [
                'scientific_name' => 'Acanthus ebracteatus',
                'common_name' => 'Black mangrove holly / sea holly',
                'family' => 'Acanthaceae',
                'genus' => 'Acanthus',
                'description' => 'A low mangrove shrub of tidal-stream margins and the inland edge of brackish forests, usually less spiny than Acanthus ilicifolius.',
                'leaf' => 'Opposite, narrow elliptic to lanceolate leaves with mostly entire or only slightly toothed margins and a pointed tip.',
                'root' => 'A spreading woody rootstock anchors soft bank soil; it has no specialized stilt roots or pneumatophores.',
                'bark' => 'Young stems are smooth and green to brown; older basal stems become gray-brown and lightly fissured.',
                'flower' => 'White to pale flowers are arranged in terminal spikes; the small bracts fall early, reflected by the name ebracteatus.',
                'fruit' => 'An ovoid capsule opens explosively and normally contains up to four flattened seeds.',
                'habitat' => ['Tidal-stream banks', 'Inland mangrove borders', 'Brackish swamps'],
                'distribution' => ['Philippines', 'South and Southeast Asia', 'Northern Australia', 'Western Pacific'],
                'zonation' => 'Landward or upper-intertidal mangrove margin within salt or brackish influence.',
                'ecological_importance' => ['Holds soft creek-bank sediment', 'Provides low vegetation cover and refuge', 'Adds flowering and seed resources to mangrove-edge food webs'],
                'conservation_status' => 'Least Concern',
                'conservation_information' => ['Protect upper mangrove margins from clearing', 'Retain tidal-stream vegetation', 'Verify flowers and leaf margins because Acanthus species are easily confused'],
                'native_status' => 'Native',
                'max_height_m' => 3,
                'history' => 'Martin Vahl published the species in 1791. Philippine botanical records place it along tidal streams and inland mangrove borders.',
                'scientific_study' => 'Useful for studies of mangrove associates, understory diversity, salt exposure, and comparison with the more strongly spined Acanthus ilicifolius.',
                'interesting_facts' => ['Its species name refers to the early loss or absence of conspicuous bracts.', 'The capsule can eject seeds when mature.', 'Leaf margins are generally less spiny than those of Acanthus ilicifolius.'],
                'references' => ['https://www.philippineplants.org/Families/Acanthaceae.html', 'https://repository.seafdec.org.ph/handle/10862/3053', 'https://www.fao.org/4/ag132e/ag132e00.pdf'],
                'cnn_candidate_availability' => 'Medium; photographs exist, but species-level review is needed because Acanthus images are frequently confused.',
            ],
            [
                'scientific_name' => 'Acanthus ilicifolius',
                'common_name' => 'Holy mangrove / sea holly / diluario',
                'family' => 'Acanthaceae',
                'genus' => 'Acanthus',
                'description' => 'A robust mangrove-edge shrub recognized by glossy holly-like leaves and showy blue-violet flowers.',
                'leaf' => 'Opposite, thick, glossy leaves with strongly toothed or spiny margins, although some shoots may be nearly entire.',
                'root' => 'A creeping woody rootstock and branching underground roots bind muddy banks; aerial roots are absent.',
                'bark' => 'Stems are green when young and become smooth gray-brown with age.',
                'flower' => 'Large pale blue to violet flowers occur in upright terminal spikes with persistent bracts.',
                'fruit' => 'A shiny ovoid capsule usually holds four large seeds and opens forcefully at maturity.',
                'habitat' => ['Brackish swamps', 'Tidal-stream margins', 'Open mangrove edges'],
                'distribution' => ['Philippines', 'South Asia', 'Southeast Asia', 'Northern Australia and western Pacific'],
                'zonation' => 'Upper intertidal and landward margins, often in open or disturbed brackish sites.',
                'ecological_importance' => ['Protects exposed creek banks', 'Provides nectar and cover at mangrove margins', 'Acts as an indicator of upper brackish habitat'],
                'conservation_status' => 'Least Concern',
                'conservation_information' => ['Protect landward mangrove buffers', 'Avoid treating native stands as weeds during rehabilitation', 'Use multiple plant parts for identification'],
                'native_status' => 'Native',
                'max_height_m' => 2,
                'history' => 'Carl Linnaeus published the species in 1753. A Philippine name published by Blanco, Acanthus doloariu, is treated as a synonym.',
                'scientific_study' => 'Frequently used in research on salt tolerance, mangrove associate zonation, pollination, and traditional plant use.',
                'interesting_facts' => ['The leaf resembles holly, which explains the name sea holly.', 'Young or shaded leaves may have fewer spines.', 'Its capsule uses a spring-like mechanism to disperse seeds.'],
                'references' => ['https://www.philippineplants.org/Families/Acanthaceae.html', 'https://repository.seafdec.org.ph/handle/10862/3053', 'https://www.fao.org/4/ag132e/ag132e00.pdf'],
                'cnn_candidate_availability' => 'High; many field images exist, but non-spiny leaves can cause confusion with related species.',
            ],
            [
                'scientific_name' => 'Acanthus volubilis',
                'common_name' => 'Climbing mangrove holly',
                'family' => 'Acanthaceae',
                'genus' => 'Acanthus',
                'description' => 'A scrambling or climbing mangrove shrub with mostly spineless leaves and a more restricted Southeast Asian distribution.',
                'leaf' => 'Opposite, narrow elliptic leaves with smooth, spineless margins and a pointed tip.',
                'root' => 'Woody basal roots anchor the climbing stems in brackish swamp soil; specialized aerial roots are absent.',
                'bark' => 'Slender stems are smooth green to brown and become woody toward the base.',
                'flower' => 'White flowers are borne in terminal spikes and contrast with the blue-violet flowers typical of Acanthus ilicifolius.',
                'fruit' => 'An ovoid seed capsule opens at maturity and disperses a small number of flattened seeds.',
                'habitat' => ['Brackish swamps', 'Tidal streams', 'Mangrove understory and margins'],
                'distribution' => ['Philippines', 'Malay Peninsula', 'Myanmar', 'Thailand', 'Andaman and Nicobar Islands'],
                'zonation' => 'Upper-intertidal understory and landward mangrove edge.',
                'ecological_importance' => ['Adds climbing and understory structure', 'Covers open bank margins', 'Improves representation of locally uncommon mangrove associates'],
                'conservation_status' => 'Least Concern',
                'conservation_information' => ['Retain intact mangrove understory', 'Document local populations because occurrences are scattered', 'Confirm climbing habit, flowers, and smooth leaf margins'],
                'native_status' => 'Native',
                'max_height_m' => 3,
                'history' => 'Nathaniel Wallich published the name in 1831. Modern Philippine records confirm scattered native populations in brackish habitats.',
                'scientific_study' => 'Valuable for comparative Acanthus taxonomy and surveys of overlooked mangrove understory diversity.',
                'interesting_facts' => ['It is the climbing member of the three Philippine mangrove Acanthus species.', 'Its leaves generally lack the holly-like spines of Acanthus ilicifolius.', 'Its scattered records make georeferenced observations especially useful.'],
                'references' => ['https://www.philippineplants.org/Families/Acanthaceae.html', 'https://repository.seafdec.org.ph/handle/10862/3053', 'https://www.fao.org/4/ag132e/ag132e00.pdf'],
                'cnn_candidate_availability' => 'Low to medium; verified public images are limited and must be separated carefully from other Acanthus species.',
            ],
            [
                'scientific_name' => 'Avicennia alba',
                'common_name' => 'White mangrove / api-api',
                'family' => 'Acanthaceae',
                'genus' => 'Avicennia',
                'description' => 'A medium to tall pioneer mangrove of muddy seaward margins, deltas, and river mouths.',
                'leaf' => 'Opposite, narrow oblong to lanceolate leaves with a sharp tip, glossy upper surface, and pale underside.',
                'root' => 'Numerous pencil-like pneumatophores rise from shallow horizontal cable roots.',
                'bark' => 'Dark gray-brown to blackish bark is relatively smooth when young and becomes lightly fissured.',
                'flower' => 'Small yellow to orange flowers occur in compact clusters.',
                'fruit' => 'Flattened egg- to pear-shaped fruit has a broad base and a distinct pointed beak.',
                'habitat' => ['Muddy seaward margins', 'River deltas', 'Estuaries'],
                'distribution' => ['Philippines', 'South Asia', 'Southeast Asia', 'Northern Australia'],
                'zonation' => 'Lower to middle intertidal, commonly acting as a seaward pioneer.',
                'ecological_importance' => ['Traps fine sediment', 'Reduces wave energy', 'Creates substrate for mangrove succession', 'Provides nursery habitat'],
                'conservation_status' => 'Least Concern',
                'conservation_information' => ['Protect pioneer mudflats from conversion', 'Maintain tidal flow', 'Compare leaves and fruits with other Avicennia species'],
                'native_status' => 'Native',
                'max_height_m' => 30,
                'history' => 'Carl Ludwig Blume published the species in 1826. It is a standard field example of a pioneer mangrove.',
                'scientific_study' => 'Studied for pneumatophore function, salt regulation, sediment capture, and early mangrove succession.',
                'interesting_facts' => ['Salt can be visible on its leaf surfaces.', 'Its narrow pointed leaves help distinguish it from Avicennia officinalis.', 'Dense pneumatophores slow water near the soil surface.'],
                'references' => ['https://www.philippineplants.org/Families/Acanthaceae.html', 'https://repository.seafdec.org.ph/handle/10862/3053', 'https://www.fao.org/4/ag132e/ag132e00.pdf'],
                'cnn_candidate_availability' => 'High; public image pools are broad, but expert review is required against other Avicennia species.',
            ],
            [
                'scientific_name' => 'Avicennia officinalis',
                'common_name' => 'Indian mangrove / api-api',
                'family' => 'Acanthaceae',
                'genus' => 'Avicennia',
                'description' => 'A broad-leaved Avicennia of inland riverbanks and relatively firm, lower-salinity mangrove mud.',
                'leaf' => 'Opposite, thick, broadly elliptic to obovate leaves are rounded at the tip and finely hairy beneath.',
                'root' => 'Pencil pneumatophores arise from shallow cable roots; low supporting roots may occur.',
                'bark' => 'Yellowish green to gray-brown bark is smooth to lightly fissured and marked by lenticels.',
                'flower' => 'Comparatively large orange-yellow flowers are hairy and grouped in dense heads.',
                'fruit' => 'Broad ovate, shortly beaked fruit has a hairy surface.',
                'habitat' => ['Inland mangrove riverbanks', 'Firm mud', 'Lower-salinity estuaries'],
                'distribution' => ['Philippines', 'South Asia', 'Southeast Asia', 'Northern Australia'],
                'zonation' => 'Middle to upper or interior mangrove, generally landward of Avicennia alba.',
                'ecological_importance' => ['Stabilizes inner riverbanks', 'Adds mature-canopy structure', 'Supports estuarine fauna and organic matter cycling'],
                'conservation_status' => 'Least Concern',
                'conservation_information' => ['Protect inland riverine stands', 'Maintain freshwater and tidal connections', 'Use leaf underside and flower traits for confirmation'],
                'native_status' => 'Native',
                'max_height_m' => 25,
                'history' => 'Carl Linnaeus published the name in 1753. The epithet officinalis reflects historical association with prepared remedies.',
                'scientific_study' => 'Useful for research on salinity gradients, riverine zonation, leaf salt management, and Avicennia taxonomy.',
                'interesting_facts' => ['Its leaves are broader than those of Avicennia alba.', 'Fine hairs are visible beneath leaves and on fruit.', 'It tends to occur farther inland than seaward pioneer species.'],
                'references' => ['https://www.philippineplants.org/Families/Acanthaceae.html', 'https://repository.seafdec.org.ph/handle/10862/3053', 'https://www.fao.org/4/ag132e/ag132e00.pdf'],
                'cnn_candidate_availability' => 'High; many candidate images exist and multi-part images can help distinguish similar Avicennia species.',
            ],
            [
                'scientific_name' => 'Nypa fruticans',
                'common_name' => 'Nipa palm / nipa / sasa',
                'family' => 'Arecaceae',
                'genus' => 'Nypa',
                'description' => 'A distinctive trunkless mangrove palm forming large stands along brackish tidal rivers.',
                'leaf' => 'Very large pinnate fronds arise at ground level; the many leaflets are long, narrow, and lanceolate.',
                'root' => 'Dense fibrous roots anchor an underground horizontal stem or rhizome.',
                'bark' => 'There is no normal above-ground barked trunk; old leaf bases surround the buried stem.',
                'flower' => 'Female flowers form a spherical terminal head while male flowers occur on catkin-like side branches.',
                'fruit' => 'Many woody wedge-shaped fruits form a large brown ball; mature fruit units separate and float.',
                'habitat' => ['Brackish tidal rivers', 'Upper estuaries', 'Soft low-salinity mud'],
                'distribution' => ['Philippines', 'South and Southeast Asia', 'Western Pacific'],
                'zonation' => 'Landward and upstream tidal zone, often in nearly pure stands.',
                'ecological_importance' => ['Stabilizes tidal banks', 'Traps sediment', 'Stores blue carbon', 'Provides habitat and sustainable community materials'],
                'conservation_status' => 'Least Concern',
                'conservation_information' => ['Maintain river hydrology', 'Use sustainable frond and sap harvesting', 'Protect nipa stands from conversion'],
                'native_status' => 'Native',
                'max_height_m' => 10,
                'history' => 'Friedrich von Wurmb described Nypa fruticans in 1779. Nipa has long supported Philippine roofing, weaving, vinegar, and sugar production.',
                'scientific_study' => 'Studied for ancient palm biogeography, estuarine carbon storage, bank stabilization, and sustainable livelihoods.',
                'interesting_facts' => ['The visible plant has no upright trunk.', 'Fossils show that Nypa relatives once had a much wider distribution.', 'Individual fruits float away from the large fruiting head.'],
                'references' => ['https://www.philippineplants.org/Families/Arecaceae.html', 'https://repository.seafdec.org.ph/handle/10862/3053', 'https://www.fao.org/4/ag132e/ag132e00.pdf'],
                'cnn_candidate_availability' => 'High; the growth form is distinctive, but the future dataset must support palm-specific plant parts.',
            ],
            [
                'scientific_name' => 'Lumnitzera racemosa',
                'common_name' => 'White-flowered black mangrove / kulasi',
                'family' => 'Combretaceae',
                'genus' => 'Lumnitzera',
                'description' => 'A small to medium upper-shore mangrove with white flowers and spoon-shaped leaves.',
                'leaf' => 'Alternate, crowded, fleshy obovate leaves usually have a rounded or shallowly notched tip.',
                'root' => 'Shallow spreading roots may form small peg-like pneumatophores in waterlogged soil.',
                'bark' => 'Gray-brown bark becomes rough and longitudinally fissured.',
                'flower' => 'Small white five-petaled flowers occur in short axillary spikes or racemes.',
                'fruit' => 'Small hard ellipsoid fruit is slightly flattened and crowned by the persistent calyx.',
                'habitat' => ['Back mangrove', 'Firm mud and sandy margins', 'Upper tidal creeks'],
                'distribution' => ['Philippines', 'Indian Ocean coasts', 'Southeast Asia', 'Western Pacific'],
                'zonation' => 'Middle to high intertidal and landward mangrove fringe.',
                'ecological_importance' => ['Stabilizes upper shores', 'Adds nectar and woody cover', 'Links tidal forest with terrestrial coastal vegetation'],
                'conservation_status' => 'Least Concern',
                'conservation_information' => ['Protect landward transition zones', 'Maintain occasional tidal flooding', 'Use flower color to separate it from Lumnitzera littorea'],
                'native_status' => 'Native',
                'max_height_m' => 10,
                'history' => 'Carl Ludwig Willdenow published the name in 1803. It is commonly paired with red-flowered Lumnitzera littorea in field keys.',
                'scientific_study' => 'Supports work on high-intertidal zonation, floral traits, drought tolerance, and mangrove-edge succession.',
                'interesting_facts' => ['Its flowers are white, unlike the red flowers of Lumnitzera littorea.', 'Leaves often look spoon-shaped.', 'It tolerates less frequent tidal flooding.'],
                'references' => ['https://www.philippineplants.org/Families/Combretaceae.html', 'https://repository.seafdec.org.ph/handle/10862/3053', 'https://www.fao.org/4/ag132e/ag132e00.pdf'],
                'cnn_candidate_availability' => 'High; flower color and leaf shape provide useful visual features.',
            ],
            [
                'scientific_name' => 'Lumnitzera littorea',
                'common_name' => 'Red-flowered black mangrove / tabao',
                'family' => 'Combretaceae',
                'genus' => 'Lumnitzera',
                'description' => 'An upper-intertidal mangrove tree distinguished by vivid red flowers and rounded fleshy leaves.',
                'leaf' => 'Alternate, crowded, thick obovate leaves have rounded, often shallowly notched tips.',
                'root' => 'Shallow lateral roots may produce small pneumatophores where soil remains waterlogged.',
                'bark' => 'Dark gray-brown bark is rough and deeply fissured on mature trunks.',
                'flower' => 'Bright red five-petaled flowers occur in terminal or axillary clusters and attract birds and insects.',
                'fruit' => 'Small woody ellipsoid fruit is flattened and retains the calyx at its tip.',
                'habitat' => ['Back mangrove', 'Sandy or firm upper shores', 'Tidal-creek margins'],
                'distribution' => ['Philippines', 'Southeast Asia', 'Northern Australia', 'Western Pacific'],
                'zonation' => 'High intertidal and landward fringe with relatively infrequent flooding.',
                'ecological_importance' => ['Stabilizes upper mangrove soils', 'Provides nectar resources', 'Adds canopy and floral diversity'],
                'conservation_status' => 'Least Concern',
                'conservation_information' => ['Protect mature red-flowering trees', 'Retain landward mangrove habitat', 'Record flowering season during surveys'],
                'native_status' => 'Native',
                'max_height_m' => 25,
                'history' => 'The accepted combination was published in the nineteenth century. Red flowers have made the species an important visual landmark in mangrove field guides.',
                'scientific_study' => 'Useful for research on pollination, phenology, high-shore tolerance, and differentiation from Lumnitzera racemosa.',
                'interesting_facts' => ['It is one of the few mangroves with conspicuous bright red flowers.', 'Flower color is a practical distinction from Lumnitzera racemosa.', 'It commonly occupies the drier edge of mangrove forest.'],
                'references' => ['https://www.philippineplants.org/Families/Combretaceae.html', 'https://repository.seafdec.org.ph/handle/10862/3053', 'https://www.fao.org/4/ag132e/ag132e00.pdf'],
                'cnn_candidate_availability' => 'Medium to high; flowering images are distinctive, while leaf-only images require expert review.',
            ],
            [
                'scientific_name' => 'Pemphis acidula',
                'common_name' => 'Bantigi / ironwood mangrove',
                'family' => 'Lythraceae',
                'genus' => 'Pemphis',
                'description' => 'A slow-growing hard-wooded shrub or small tree of coral rock, limestone, and exposed high-tide shores.',
                'leaf' => 'Opposite, small, thick gray-green leaves are narrowly elliptic to oblong.',
                'root' => 'Strong roots spread through rock crevices and surface substrate without conspicuous aerial roots.',
                'bark' => 'Rough gray-brown bark bears prominent lenticels and becomes deeply fissured.',
                'flower' => 'Small solitary white flowers usually have six crinkled petals.',
                'fruit' => 'Small urn- or cup-shaped capsules remain enclosed by a persistent calyx.',
                'habitat' => ['Coral rock and limestone shores', 'Exposed high-tide coast', 'Sandy upper margins'],
                'distribution' => ['Philippines', 'Tropical Indian Ocean', 'Southeast Asia', 'Pacific islands'],
                'zonation' => 'High intertidal to supratidal edge on rock, coral, or sand.',
                'ecological_importance' => ['Anchors exposed rocky margins', 'Tolerates salt spray', 'Provides habitat at the upper mangrove limit'],
                'conservation_status' => 'Least Concern globally; Endangered in the Philippines',
                'conservation_information' => ['Prevent illegal collection and cutting', 'Protect naturally slow-growing stands', 'Exclude shaped bonsai plants from wild-reference datasets'],
                'native_status' => 'Native',
                'max_height_m' => 11,
                'history' => 'Johann and Georg Forster published the species in 1776. Its dense wood has driven collection for construction and bonsai.',
                'scientific_study' => 'Important for studies of salt spray, rocky-shore zonation, slow growth, wood density, and collection pressure.',
                'interesting_facts' => ['Its wood is exceptionally dense.', 'It grows where many muddy-forest mangroves cannot.', 'Bonsai-shaped examples should not define the normal wild growth form.'],
                'references' => ['https://www.philippineplants.org/Families/Lythraceae.html', 'https://powo.science.kew.org/taxon/urn:lsid:ipni.org:names:554064-1', 'https://www.philippineplants.org/Resources/dao-2017-11.pdf'],
                'cnn_candidate_availability' => 'Medium to high; wild and cultivated images exist, but bonsai images need separate tagging or exclusion.',
            ],
            [
                'scientific_name' => 'Sonneratia ovata',
                'common_name' => 'Mangrove apple / pedada',
                'family' => 'Lythraceae',
                'genus' => 'Sonneratia',
                'description' => 'A locally uncommon back-mangrove Sonneratia with broad leaves and flowers that usually lack petals.',
                'leaf' => 'Opposite, thick, broad ovate to nearly circular leaves have a rounded tip.',
                'root' => 'Short conical pneumatophores rise from cable roots in soft waterlogged mud.',
                'bark' => 'Brown bark is rough and lightly fissured.',
                'flower' => 'Dusk-opening flowers have red-tinged sepals, many pale stamens, and usually no petals.',
                'fruit' => 'Pear-shaped to rounded green berries sit in a persistent star-like calyx.',
                'habitat' => ['Back mangrove', 'Low-salinity muddy sites', 'Upper estuaries'],
                'distribution' => ['Philippines', 'Southeast Asia', 'Western Pacific'],
                'zonation' => 'High intertidal or landward, fresh-to-brackish mangrove habitat.',
                'ecological_importance' => ['Adds rare-species diversity', 'Provides fruit and floral resources', 'Can indicate low-salinity back-mangrove conditions'],
                'conservation_status' => 'Near Threatened',
                'conservation_information' => ['Document and protect local populations', 'Avoid collecting rare reproductive material', 'Confirm petal absence and broad leaf shape'],
                'native_status' => 'Native',
                'max_height_m' => 20,
                'history' => 'Cornelis Backer published the species in 1920. Philippine records are scattered and make verified observations valuable.',
                'scientific_study' => 'Useful for rare-species monitoring and comparison with Sonneratia alba and Sonneratia caseolaris.',
                'interesting_facts' => ['Its flowers usually have no petals.', 'Leaves can be almost circular.', 'It tends to occur farther inland than Sonneratia alba.'],
                'references' => ['https://www.philippineplants.org/Families/Lythraceae.html', 'https://repository.seafdec.org.ph/handle/10862/3053', 'https://www.fao.org/4/ag132e/ag132e00.pdf'],
                'cnn_candidate_availability' => 'Medium; rarity limits balanced collection and labels need expert confirmation.',
            ],
            [
                'scientific_name' => 'Camptostemon philippinensis',
                'common_name' => 'Gapas-gapas',
                'family' => 'Malvaceae',
                'genus' => 'Camptostemon',
                'description' => 'A rare soft-wooded mangrove native to the Philippines and Sulawesi, usually found along tidal creeks and mangrove margins.',
                'leaf' => 'Obovate to elliptic-lanceolate leaves are crowded near twig ends and retain fine scales on both surfaces.',
                'root' => 'Surface roots may form knobby pneumatophores around a gnarled trunk base.',
                'bark' => 'Gray to brown bark is longitudinally fissured and marked with lenticels.',
                'flower' => 'Tiny white five-petaled flowers occur in crowded axillary clusters and have five stamens.',
                'fruit' => 'Capsule-like fruits release small seeds covered in conspicuous white cottony hairs.',
                'habitat' => ['Tidal creeks', 'Mangrove margins', 'Sheltered intertidal forest'],
                'distribution' => ['Philippines', 'Sulawesi'],
                'zonation' => 'Mangrove edge and tidal-creek habitat, including the lower intertidal zone.',
                'ecological_importance' => ['Adds rare-species diversity', 'Contributes creek-edge forest structure', 'Provides a conservation indicator for intact mangrove habitat'],
                'conservation_status' => 'Endangered',
                'conservation_information' => ['Protect every known population', 'Use non-destructive field documentation', 'Do not publish sensitive coordinates without expert review'],
                'native_status' => 'Native',
                'max_height_m' => 20,
                'history' => 'Sebastian Vidal described its basionym in 1885, and Odoardo Beccari published the accepted combination in 1889.',
                'scientific_study' => 'Leaf scales, five-stamen flowers, cottony seed hairs, and its restricted range are important identification and conservation-study features.',
                'interesting_facts' => ['Its common name refers to the cotton-like seed hairs.', 'The accepted spelling is philippinensis.', 'It is a high-priority species for Philippine mangrove conservation.'],
                'references' => ['https://www.worldfloraonline.org/taxon/wfo-0000583114', 'https://www.fao.org/4/ag132e/ag132e08.pdf', 'https://erdbservices.denr.gov.ph/eskris/iec_for_guest.php?operation=view&pk0=584'],
                'cnn_candidate_availability' => 'Low to medium; use only licensed, expert-verified images of wild plants.',
            ],
            [
                'scientific_name' => 'Heritiera littoralis',
                'common_name' => 'Looking-glass mangrove / dungon-late',
                'family' => 'Malvaceae',
                'genus' => 'Heritiera',
                'description' => 'A large coastal and back-mangrove tree recognized by silvery leaf undersides and strongly keeled fruits.',
                'leaf' => 'Alternate leathery leaves are green above and densely silver to coppery-scaled beneath.',
                'root' => 'Mature trees develop strong plank buttresses; pneumatophores are generally absent.',
                'bark' => 'Pale gray to pinkish-gray bark becomes fissured or flaky with age.',
                'flower' => 'Small unisexual reddish-purple to brownish bell-shaped flowers occur in branched clusters.',
                'fruit' => 'The hard one-seeded woody fruit has a conspicuous raised keel that aids flotation.',
                'habitat' => ['Back mangrove', 'Tidal riverbanks', 'Sandy or rocky landward margins'],
                'distribution' => ['Philippines', 'Indian Ocean tropics', 'Southeast Asia', 'Western Pacific'],
                'zonation' => 'Landward mangrove and coastal-forest transition with less frequent inundation.',
                'ecological_importance' => ['Stabilizes landward margins', 'Provides tall-canopy habitat', 'Links mangrove and coastal forest communities'],
                'conservation_status' => 'Least Concern',
                'conservation_information' => ['Protect mature trees and buttress-root zones', 'Retain the landward transition forest', 'Monitor natural regeneration'],
                'native_status' => 'Native',
                'max_height_m' => 25,
                'history' => 'The name was published in 1789. Older references placed the genus in Sterculiaceae, now included in Malvaceae.',
                'scientific_study' => 'Useful for studies of water-dispersed fruits, coastal canopy structure, and mangrove-to-beach-forest zonation.',
                'interesting_facts' => ['The silver leaf underside flashes in the wind like a mirror.', 'Its keeled fruit can float.', 'Mature trees form large plank buttresses.'],
                'references' => ['https://www.philippineplants.org/Families/Sterculiaceae.html', 'https://repository.seafdec.org.ph/handle/10862/3053', 'https://www.fao.org/4/ag132e/ag132e00.pdf'],
                'cnn_candidate_availability' => 'High; leaves, buttresses, and keeled fruits provide strong visual features.',
            ],
            [
                'scientific_name' => 'Xylocarpus rumphii',
                'common_name' => 'Puzzle-nut tree / piagao',
                'family' => 'Meliaceae',
                'genus' => 'Xylocarpus',
                'description' => 'A coastal Xylocarpus of exposed rocky or sandy shores, historically reported in Philippine guides as Xylocarpus moluccensis.',
                'leaf' => 'Opposite compound leaves have two to four pairs of leathery ovate to heart-shaped leaflets with pointed tips.',
                'root' => 'Conspicuous buttresses and pneumatophores are generally absent.',
                'bark' => 'Finely fissured gray bark covers pink to red inner bark.',
                'flower' => 'Creamy-white four-petaled flowers occur in long, loose, hanging clusters.',
                'fruit' => 'Round woody fruits contain several irregular interlocking puzzle-like seeds.',
                'habitat' => ['Rocky coasts and cliffs', 'Exposed shores', 'Sand near the high-water line'],
                'distribution' => ['Philippines', 'East Africa to Malesia', 'Northern Australia', 'Western Pacific'],
                'zonation' => 'High coastal fringe near or above the normal high-water line.',
                'ecological_importance' => ['Stabilizes exposed coastal margins', 'Provides woody habitat', 'Represents the beach-to-mangrove transition'],
                'conservation_status' => 'Least Concern',
                'conservation_information' => ['Protect mature coastal trees', 'Record substrate during surveys', 'Keep Xylocarpus moluccensis as a searchable historical alias'],
                'native_status' => 'Native',
                'max_height_m' => 15,
                'history' => 'David Mabberley published the accepted combination in 1982. The name honors the Malesian naturalist Georg Eberhard Rumphius.',
                'scientific_study' => 'Current Philippine flora treats older Philippine use of Xylocarpus moluccensis as a misapplied name for this species.',
                'interesting_facts' => ['Its seeds fit together like puzzle pieces.', 'It usually lacks the large buttresses of Xylocarpus granatum.', 'Older Philippine sources may call it Xylocarpus moluccensis.'],
                'references' => ['https://www.philippineplants.org/Families/Meliaceae.html', 'https://www.nparks.gov.sg/florafaunaweb/flora/3/2/3210', 'https://www.fao.org/4/ag132e/ag132e00.pdf'],
                'cnn_candidate_availability' => 'Medium; historical-name confusion requires strict taxonomic review of images.',
            ],
            [
                'scientific_name' => 'Osbornia octodonta',
                'common_name' => 'Myrtle mangrove / bunot-bunot',
                'family' => 'Myrtaceae',
                'genus' => 'Osbornia',
                'description' => 'An aromatic salt-tolerant shrub or small tree of exposed coral, rocky, and sandy shores.',
                'leaf' => 'Small opposite brittle leaves contain visible oil glands and are aromatic when crushed.',
                'root' => 'Cable-like surface roots may be exposed across rock or sand.',
                'bark' => 'Thick spongy gray-brown bark is deeply and longitudinally fissured.',
                'flower' => 'Small white flowers occur singly or in small groups.',
                'fruit' => 'Small dry capsules distinguish it from mangroves with fleshy berries or long propagules.',
                'habitat' => ['Rocky and coral shores', 'Sandy high intertidal', 'Exposed saline coast'],
                'distribution' => ['Philippines', 'Malesia', 'Northern Australia', 'Western Pacific'],
                'zonation' => 'Middle to high intertidal on exposed rocky, coral-derived, or sandy substrate.',
                'ecological_importance' => ['Stabilizes exposed shore margins', 'Occupies a high-salinity niche', 'Adds habitat where muddy-forest mangroves do not persist'],
                'conservation_status' => 'Least Concern',
                'conservation_information' => ['Protect exposed rocky-shore habitat', 'Record substrate during surveys', 'Use aroma only with visual traits and without damaging plants'],
                'native_status' => 'Native',
                'max_height_m' => 7,
                'history' => 'Ferdinand von Mueller published the species in 1862. It is the only currently accepted species in its genus.',
                'scientific_study' => 'Useful for studies of exposed-shore zonation, salinity tolerance, aromatic oils, and substrate specialization.',
                'interesting_facts' => ['It is the sole species of Osbornia.', 'Its crushed leaves are aromatic.', 'It commonly grows on rock, coral, or sand rather than deep mud.'],
                'references' => ['https://www.philippineplants.org/Families/Myrtaceae.html', 'https://repository.seafdec.org.ph/handle/10862/3053', 'https://www.fao.org/4/ag132e/ag132e00.pdf'],
                'cnn_candidate_availability' => 'Medium; photographs exist, but verified multi-part field images are needed.',
            ],
            [
                'scientific_name' => 'Aegiceras corniculatum',
                'common_name' => 'River mangrove / saging-saging',
                'family' => 'Primulaceae',
                'genus' => 'Aegiceras',
                'description' => 'A widespread small evergreen mangrove of sheltered tidal waterways, muddy estuaries, and creek banks.',
                'leaf' => 'Alternate leathery obovate to elliptic leaves have rounded or shallowly notched tips and may show surface salt.',
                'root' => 'Shallow spreading surface roots anchor firm mud; conspicuous specialized aerial roots are usually absent.',
                'bark' => 'Smooth gray-brown bark is marked with lenticels.',
                'flower' => 'Fragrant white flowers occur in rounded clusters.',
                'fruit' => 'The narrow curved horn-like fruit is cryptoviviparous and develops a pointed seedling inside.',
                'habitat' => ['Sheltered estuaries', 'Tidal creeks', 'Muddy riverbanks'],
                'distribution' => ['Philippines', 'South Asia', 'Southeast Asia', 'Western Pacific'],
                'zonation' => 'Middle to upper intertidal along sheltered tidal waterways.',
                'ecological_importance' => ['Stabilizes creek banks', 'Provides fragrant flowers for pollinators', 'Adds understory cover in sheltered mangroves'],
                'conservation_status' => 'Least Concern',
                'conservation_information' => ['Protect tidal-creek vegetation', 'Maintain estuarine hydrology', 'Confirm curved fruit and clustered white flowers'],
                'native_status' => 'Native',
                'max_height_m' => 8,
                'history' => 'The species was first described under another genus in 1754; Francisco Manuel Blanco published the accepted combination in 1837.',
                'scientific_study' => 'Useful for research on cryptovivipary, salt management, sheltered-estuary zonation, and pollination.',
                'interesting_facts' => ['Its curved fruit resembles a small horn.', 'Salt may crystallize on its leaves.', 'The seed begins developing while the fruit remains attached.'],
                'references' => ['https://www.philippineplants.org/Families/Primulaceae.html', 'https://repository.seafdec.org.ph/handle/10862/3053', 'https://www.fao.org/4/ag132e/ag132e00.pdf'],
                'cnn_candidate_availability' => 'High; curved fruits and clustered flowers are useful visual features.',
            ],
            [
                'scientific_name' => 'Aegiceras floridum',
                'common_name' => 'Flowering mangrove / tinduk-tindukan',
                'family' => 'Primulaceae',
                'genus' => 'Aegiceras',
                'description' => 'A small Malesian mangrove of exposed rocky, coral, or sandy high-intertidal shores.',
                'leaf' => 'Small leathery obovate leaves have rounded tips and may excrete salt.',
                'root' => 'Shallow surface roots spread through rocky or sandy substrate.',
                'bark' => 'Dark mottled bark is marked with lenticels.',
                'flower' => 'White flowers occur along branched stalks.',
                'fruit' => 'Small curved fruits mature from green to a distinctive bright red.',
                'habitat' => ['Rocky and coral shores', 'Sandy high intertidal', 'Exposed saline coast'],
                'distribution' => ['Philippines', 'Malesia'],
                'zonation' => 'High intertidal fringe on exposed hard or sandy substrate.',
                'ecological_importance' => ['Stabilizes exposed upper shores', 'Adds fruit and flower resources', 'Represents a restricted high-salinity habitat'],
                'conservation_status' => 'Near Threatened',
                'conservation_information' => ['Document and protect local populations', 'Protect rocky and coral-derived substrate', 'Use the red fruit and exposed habitat to separate it from Aegiceras corniculatum'],
                'native_status' => 'Native',
                'max_height_m' => 5,
                'history' => 'The accepted name was published by Roemer and Schultes in 1819.',
                'scientific_study' => 'Useful for monitoring a relatively restricted Malesian mangrove and comparing substrate specialization within Aegiceras.',
                'interesting_facts' => ['Its mature curved fruits can be bright red.', 'It favors more exposed shores than Aegiceras corniculatum.', 'Its restricted distribution increases its monitoring value.'],
                'references' => ['https://www.philippineplants.org/Families/Primulaceae.html', 'https://powo.science.kew.org/taxon/urn:lsid:ipni.org:names:586620-1', 'https://repository.seafdec.org.ph/handle/10862/3053'],
                'cnn_candidate_availability' => 'Medium; fruiting images are distinctive but verified Philippine coverage is limited.',
            ],
            [
                'scientific_name' => 'Bruguiera cylindrica',
                'common_name' => 'Small-leaved orange mangrove / pototan',
                'family' => 'Rhizophoraceae',
                'genus' => 'Bruguiera',
                'description' => 'A medium true mangrove of sheltered estuaries and firm muddy or clay-rich substrates.',
                'leaf' => 'Opposite glossy elliptic leaves have pointed tips.',
                'root' => 'Looping knee roots and short buttresses provide aeration and support.',
                'bark' => 'Gray bark is smooth to finely fissured.',
                'flower' => 'Clustered flowers have a green eight-lobed calyx and white petals with bristled tips.',
                'fruit' => 'Thin smooth cylindrical propagules commonly grow about 8 to 15 centimeters long.',
                'habitat' => ['Sheltered estuaries', 'Firm clay or mud', 'Interior mangrove forest'],
                'distribution' => ['Philippines', 'South Asia', 'Southeast Asia', 'Northern Australia'],
                'zonation' => 'Middle intertidal in sheltered estuaries and interior mangrove stands.',
                'ecological_importance' => ['Stabilizes firm muddy substrate', 'Adds knee-root habitat', 'Supports sheltered-estuary forest structure'],
                'conservation_status' => 'Least Concern',
                'conservation_information' => ['Protect sheltered estuarine stands', 'Match restoration sites to firm substrate', 'Verify clustered flowers and slender propagules'],
                'native_status' => 'Native',
                'max_height_m' => 20,
                'history' => 'Carl Linnaeus first described it under Rhizophora in 1753, and Carl Ludwig Blume published the accepted Bruguiera combination in 1827.',
                'scientific_study' => 'Useful for comparing knee roots, propagule form, and stand structure within Bruguiera.',
                'interesting_facts' => ['Its flowers are clustered rather than solitary.', 'Looping knee roots can emerge above the mud.', 'Its propagules are more slender than those of several related species.'],
                'references' => ['https://www.philippineplants.org/Families/Rhizophoraceae.html', 'https://repository.seafdec.org.ph/handle/10862/3053', 'https://www.fao.org/4/ag132e/ag132e00.pdf'],
                'cnn_candidate_availability' => 'High; public images are available, but flower and propagule views should accompany leaves.',
            ],
            [
                'scientific_name' => 'Bruguiera sexangula',
                'common_name' => 'Upriver orange mangrove / pototan',
                'family' => 'Rhizophoraceae',
                'genus' => 'Bruguiera',
                'description' => 'A large upriver mangrove of lower-salinity waterways and interior forest that is flooded less often.',
                'leaf' => 'Large opposite leathery elliptic leaves have acute tips.',
                'root' => 'Knee roots, flanged buttresses, and occasional low stilt roots support mature trees.',
                'bark' => 'Pale gray to gray-brown bark is smooth to lightly fissured.',
                'flower' => 'Large pendulous usually solitary flowers have a yellowish calyx divided into about 10 to 14 lobes.',
                'fruit' => 'Short thick propagules are angular and characteristically six-sided in cross-section.',
                'habitat' => ['Upper tidal rivers', 'Interior mangrove forest', 'Lower-salinity waterways'],
                'distribution' => ['Philippines', 'South and Southeast Asia', 'Northern Australia', 'Western Pacific'],
                'zonation' => 'Upper and interior mangrove along lower-salinity tidal waterways.',
                'ecological_importance' => ['Stabilizes upper tidal banks', 'Provides tall-canopy habitat', 'Adds structure to lower-salinity mangrove reaches'],
                'conservation_status' => 'Least Concern',
                'conservation_information' => ['Protect upriver stands', 'Maintain freshwater and tidal flows', 'Confirm the large flower and angular propagule'],
                'native_status' => 'Native',
                'max_height_m' => 30,
                'history' => 'Joao de Loureiro described the basionym in 1790, and Jean Louis Marie Poiret published the accepted combination in 1816.',
                'scientific_study' => 'Useful for research on upriver zonation and comparison with Bruguiera gymnorrhiza and Bruguiera cylindrica.',
                'interesting_facts' => ['The name sexangula refers to the propagule\'s six angles.', 'It commonly grows farther upriver than seaward Bruguiera stands.', 'Its flowers are comparatively large.'],
                'references' => ['https://www.philippineplants.org/Families/Rhizophoraceae.html', 'https://www.worldfloraonline.org/taxon/wfo-0000572763', 'https://repository.seafdec.org.ph/handle/10862/3053'],
                'cnn_candidate_availability' => 'High; propagules and flowers offer strong features, but related Bruguiera species require expert review.',
            ],
            [
                'scientific_name' => 'Ceriops zippeliana',
                'common_name' => 'Malatangal / Ceriops',
                'family' => 'Rhizophoraceae',
                'genus' => 'Ceriops',
                'description' => 'A relatively uncommon Southeast Asian Ceriops now recognized as distinct from the South Asian Ceriops decandra.',
                'leaf' => 'Opposite leathery leaves are oval to elliptical and often clustered near twig ends.',
                'root' => 'Knee roots and a low buttressed base may develop in firm mud.',
                'bark' => 'Gray-brown bark is smooth to lightly fissured.',
                'flower' => 'Flowers form a simple compact head-like inflorescence with one layer of bracts.',
                'fruit' => 'A shallow disc-like calyx surrounds the fruit; the thick propagule is uneven in width and narrows to an acute tip.',
                'habitat' => ['Firm muddy shores', 'Sheltered mangrove edge', 'Interior mangrove forest'],
                'distribution' => ['Philippines', 'Malay Peninsula', 'Borneo', 'Java', 'Sulawesi'],
                'zonation' => 'Middle to upper intertidal edges and firm interior mud.',
                'ecological_importance' => ['Stabilizes mangrove-edge sediment', 'Adds understory structure', 'Improves locally uncommon species coverage'],
                'conservation_status' => 'Least Concern globally; locally uncommon in the Philippines',
                'conservation_information' => ['Document Philippine populations', 'Do not automatically label Philippine material Ceriops decandra', 'Compare inflorescence, calyx, and propagule with Ceriops tagal'],
                'native_status' => 'Native',
                'max_height_m' => 15,
                'history' => 'Carl Ludwig Blume described the species in the nineteenth century. Morphological and molecular work published in 2009 supported its separation from Ceriops decandra.',
                'scientific_study' => 'It is a useful example of how molecular and morphological evidence can correct long-used regional species names.',
                'interesting_facts' => ['Older Philippine references may call it Ceriops decandra.', 'Its compact inflorescence helps separate it from related species.', 'Taxonomic confirmation is important before training a model.'],
                'references' => ['https://www.philippineplants.org/Families/Rhizophoraceae.html', 'https://bioportal.naturalis.nl/taxon/Ceriops_zippeliana', 'https://pmc.ncbi.nlm.nih.gov/articles/PMC10848689/'],
                'cnn_candidate_availability' => 'Low; public observations are sparse and are frequently confused with related Ceriops species.',
            ],
            [
                'scientific_name' => 'Scyphiphora hydrophylacea',
                'common_name' => 'Nilad',
                'family' => 'Rubiaceae',
                'genus' => 'Scyphiphora',
                'description' => 'A glossy-leaved shrub or small mangrove tree with fragrant pale flowers and distinctly grooved fruits.',
                'leaf' => 'Opposite glossy leathery obovate to elliptic leaves have rounded tips.',
                'root' => 'Surface roots and occasional small stilt roots may occur.',
                'bark' => 'Brownish-gray bark is smooth to lightly fissured.',
                'flower' => 'Small fragrant pale-pink to white flowers occur in dense axillary clusters.',
                'fruit' => 'Fleshy ellipsoid fruits change from green to yellow and brown and have six to ten strong longitudinal grooves.',
                'habitat' => ['Backshore mangrove', 'Firm or sandy mud', 'Saline and brackish tidal streams'],
                'distribution' => ['Philippines', 'Indian Ocean tropics', 'Southeast Asia', 'Western Pacific'],
                'zonation' => 'Middle to high intertidal and landward mangrove fringe.',
                'ecological_importance' => ['Stabilizes inner shorelines', 'Provides flowers and fruit for coastal fauna', 'Adds high-intertidal shrub habitat'],
                'conservation_status' => 'Least Concern',
                'conservation_information' => ['Protect landward mangrove habitat', 'Confirm grooved fruits during surveys', 'Present the Manila name association as tradition rather than settled fact'],
                'native_status' => 'Native',
                'max_height_m' => 10,
                'history' => 'Carl Friedrich Gaertner published the name in 1806. Historical Philippine names such as Ixora manilana are treated as synonyms.',
                'scientific_study' => 'Useful for Rubiaceae identification, high-intertidal zonation, pollination, and Philippine cultural-history lessons.',
                'interesting_facts' => ['The accepted spelling has one l in hydrophylacea.', 'Its fruit has prominent longitudinal grooves.', 'Nilad is traditionally associated with the name Maynilad or Manila.'],
                'references' => ['https://www.philippineplants.org/Families/Rubiaceae.html', 'https://powo.science.kew.org/taxon/urn:lsid:ipni.org:names:73566-3', 'https://www.nparks.gov.sg/florafaunaweb/flora/2/4/2444'],
                'cnn_candidate_availability' => 'Medium to high; grooved fruit is distinctive, while leaf-only records need review.',
            ],
        ];
    }
}
